language: node_js
node_js:
  - 11.13.0
cashe: npm
script:
  - npm ci
  - npm install --global workbox-cli
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
